num1=float(input("Enter First Number : "))
num2=float(input("Enter Second Number : "))
num3=float(input("Enter Third Number : "))
num4=float(input("Enter Fourth Number : "))
if(num1>num2 and num1>num3 and num1>num4):print(f"{num1} is the largest number.")
elif(num2>num3 and num2>num4):print(f"{num2} is the largest number.")
elif(num3>num4):print(f"{num3} is the largest number.")
else:print(f"{num4} is the largest number.")